- name:  disable nodejs default version
  ansible.builtin.shell: dnf module disable nginx -y

- name:  enabling Nginx 1.24
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name:  installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Creating a  nginx conf file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup APP prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Enabling nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true